name: Lint and Tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.1.2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm i
      - run: pnpm lint
      # - run: pnpm test
      - name: Check locales are up to date with tolgee

        env:
          TOLGEE_ACCESS_TOKEN: ${{ secrets.TOLGEE_ACCESS_TOKEN }}
        run: |
          node ./scripts/update-locales.js

          if [[ `git status --porcelain` ]]; then
            echo "❌ Please update locales with tolgee and commit changes"
            echo "Changes detected:"
            git diff
            exit 1
          else
            echo "✅ Locales are up to date"
          fi
